[package]
name = "lyrical-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = ["native-tls-vendored", "blocking", "json"] }
scraper = "0.22.0"
serde_json = "1.0.128"
